root: ./dist

require: []

ignore:
  - assets/*
  - locales/*
  - templates/*(markup)
  - sections/*markup.liquid
  - templates/*markup.liquid
  - snippets/*markup.liquid
  - templates/page.typography.liquid
  - templates/page.typography.liquid
  - templates/product.markup-2.liquid

ConvertIncludeToRender:
  enabled: true

LiquidTag:
  enabled: true
  min_consecutive_statements: 4

MissingTemplate:
  enabled: true

NestedSnippet:
  enabled: true
  max_nesting_level: 4

RequiredLayoutThemeObject:
  enabled: true

SpaceInsideBraces:
  enabled: true

SyntaxError:
  enabled: true

TemplateLength:
  enabled: true
  max_length: 350
  # Exclude content of {% schema %} in line count
  exclude_schema: true

UnknownFilter:
  enabled: true

UnusedAssign:
  enabled: true

UnusedSnippet:
  enabled: true

MatchingSchemaTranslations:
  enabled: true

MatchingTranslations:
  enabled: true

DefaultLocale:
  enabled: false

TranslationKeyExists:
  enabled: true

ValidHTMLTranslation:
  enabled: true

ValidJson:
  enabled: true

ValidSchema:
  enabled: true

MissingRequiredTemplateFiles:
  enabled: true

UndefinedObject:
  enabled: true
  exclude_snippets: true

RequiredDirectories:
  enabled: true

DeprecatedFilter:
  enabled: true

MissingEnableComment:
  enabled: true

ParserBlockingJavaScript:
  enabled: true

AssetSizeJavaScript:
  enabled: false
  threshold_in_bytes: 10_000

RemoteAsset:
  enabled: false

ImgLazyLoading:
  enabled: false

DeprecateLazysizes:
  enabled: false

AssetSizeCSS:
  enabled: false
  threshold_in_bytes: 100_000

ImgWidthAndHeight:
  enabled: false
