#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! [ -x "$(command -v yarn)" ]; then
  echo 'yarn not found. Probably running within the pipeline. Skipping pre-push hook.' >&2
else
    yarn e2e:run
fi
