name: ThemeCheck

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build

  theme-check:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install Shopify/theme-check
        run: gem install theme-check
      - name: Run theme-check
        run: theme-check
